version: "3.8"
name: "vita_nail"
services:
  db:
    container_name: "db_vitanail"
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${NAME}
    ports:
      - "${PORT}:5432"
    networks:
      - postgres
  tgbot:
    container_name: "tgbot"
    image: tgbot:latest
    restart: always
    env_file:
      - path: .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "8000"
networks:
  postgres:
    driver: bridge
volumes:
  postgres: