version: "4.28"
services:
  db:
    container_name: "db_vitanail"
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
      - POSTGRES_DB=${NAME}
    ports:
      - "${PORT}:5432"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge
volumes:
  postgres: