# Generated by Django 5.0.2 on 2024-03-09 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.AlterModelOptions(
            name='window',
            options={'get_latest_by': 'date', 'ordering': ['-date'], 'verbose_name': 'Окошко', 'verbose_name_plural': 'Окошки'},
        ),
        migrations.RemoveField(
            model_name='window',
            name='id',
        ),
        migrations.AddField(
            model_name='window',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='window',
            name='date',
            field=models.DateTimeField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='window',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
