# Generated by Django 5.0.2 on 2024-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_window_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
    ]
