# Generated by Django 5.0.2 on 2024-03-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_alter_window_options_remove_window_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='window',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='user',
            new_name='client',
        ),
    ]
